### ISSUE TITLE
Resolve not working

### ISSUE THREAD

**Issue by JCHELIX** [DonutsNL/ticketfilter#10]
Hi 
It seem's that the plugin isn't putting the ticket at the resolved status for this string inside the subjects

string "L'incident num INC0034498, Disfonctionnement des MAPs PRTG a été clôturé."

ticket match string : /.*?(?<match>(RITM|INC)[0-9]{7}).*/
Solved match string : /.*?(?<solved>(RESOLU |clôturé|Clôturé).*/

<img width="687" alt="image" src="https://github.com/DonutsNL/ticketfilter/assets/150350926/0a230087-964e-437e-83ab-a60cc1d166a3">

many thank for help on this.

**Comment by DonutsNL** [comment]
Hi @JCHELIX ,

Thanks for sharing this issue.
I will dive into this issue somewhere this weekend.

rgrds,

**Comment by JCHELIX** [comment]
[2023-11-24 13:38:12] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function xpath() on null in /glpi/src/RichText/UserMention.php at line 207
  Backtrace :
  src/RichText/UserMention.php:91                    Glpi\RichText\UserMention::getUserIdsFromUserMentions()
  src/CommonDBTM.php:1538                            Glpi\RichText\UserMention::handleUserMentions()
  src/CommonDBTM.php:1324                            CommonDBTM->post_addItem()
  src/CronTask.php:369                               CommonDBTM->add()
  src/MailCollector.php:1916                         CronTask->log()
  src/CronTask.php:1018                              MailCollector::cronMailgate()
  front/cron.php:84                                  CronTask::launch()

usrloc@IKLSRV20002:/opt/dockervol/glpi/files/_log$ tail -n 100  php-errors.log
  marketplace/ticketfilter/src/Filter.php:70         GlpiPlugin\Ticketfilter\Filter::searchForMatches()
  src/Plugin.php:1665                                GlpiPlugin\Ticketfilter\Filter::PreItemAdd()
  src/CommonDBTM.php:1275                            Plugin::doHook()
  front/ticket.form.php:74                           CommonDBTM->add()

[2023-11-24 12:48:59] glpiphplog.WARNING:   *** PHP User Warning (512): TicketFilter: PregMatch failed! please review the Solved pattern /.*?(?<solved>(RESOLU |clôturé|Clôturé|- Clôtu).*/ and correct it in /glpi/marketplace/ticketfilter/src/TicketHandler.php at line 301
  Backtrace :
  marketplace/ticketfilter/src/TicketHandler.php:301 trigger_error()
  marketplace/ticketfilter/src/Filter.php:143        GlpiPlugin\Ticketfilter\TicketHandler->processTicket()
  marketplace/ticketfilter/src/Filter.php:70         GlpiPlugin\Ticketfilter\Filter::searchForMatches()
  src/Plugin.php:1665                                GlpiPlugin\Ticketfilter\Filter::PreItemAdd()
  src/CommonDBTM.php:1275                            Plugin::doHook()
  front/ticket.form.php:74                           CommonDBTM->add()

**Comment by JCHELIX** [comment]
It seem's thaht my REGEXE patern isn't correct
/.*?(?<solved>(RESOLU |clôturé|Clôturé|- Clôtu).*/

can you help me out on this ?

**Comment by JCHELIX** [comment]
<img width="755" alt="image" src="https://github.com/DonutsNL/ticketfilter/assets/150350926/c160614e-34ce-4a5b-9d56-a274a329e1af">

**Comment by ChrisGralike** [comment]
First glance the ( ,,, ) are not correct. Try: the following pattern instead.
![image](https://github.com/DonutsNL/ticketfilter/assets/138442033/0c496fd5-ef27-4e9c-953c-de46f0d2eb66)

**Comment by JCHELIX** [comment]
<img width="811" alt="image" src="https://github.com/DonutsNL/ticketfilter/assets/150350926/f2dc21b3-ba64-45cb-a850-e7a9283d1db7">
/.*?(?<solved>Clôturé).*/

**Comment by JCHELIX** [comment]
[2023-11-24 14:30:40] glpiphplog.WARNING:   *** PHP User Warning (512): TicketFilter: Length ofClôturé is longer then allowed by configured Ticket Match String Length in /glpi/marketplace/ticketfilter/src/TicketHandler.php at line 297
  Backtrace :
  marketplace/ticketfilter/src/TicketHandler.php:297 trigger_error()
  marketplace/ticketfilter/src/Filter.php:143        GlpiPlugin\Ticketfilter\TicketHandler->processTicket()
  marketplace/ticketfilter/src/Filter.php:70         GlpiPlugin\Ticketfilter\Filter::searchForMatches()
  src/Plugin.php:1665                                GlpiPlugin\Ticketfilter\Filter::PreItemAdd()
  src/CommonDBTM.php:1275                            Plugin::doHook()
  front/ticket.form.php:74                           CommonDBTM->add()

**Comment by JCHELIX** [comment]
Ok extended "Solved match group length"  to 9 ==> this is now working

**Comment by ChrisGralike** [comment]
Thats great! 👍
