### ISSUE TITLE
Intall error

### ISSUE THREAD

**Issue by AlexTR85** [DonutsNL/ticketfilter#8]
Hello I have a lot of pluggins installed, but for this plugn i have this error:
![image](https://github.com/DonutsNL/ticketfilter/assets/56876938/cbc070c7-7f87-4f7f-a909-eac76cb94925)

Thankyou

**Comment by AlexTR85** [comment]
![image](https://github.com/DonutsNL/ticketfilter/assets/56876938/dc889657-2f0e-4083-973e-80134059e4fc)
aps...

**Comment by DonutsNL** [comment]
Yeah i was going to say. Make sure zip is enabled and the system meets its requirements.

Review: https://www.php.net/manual/en/zip.requirements.php for more information.

Rgrds,
